### ISSUE TITLE
add update on save option

### ISSUE THREAD

**Issue by ghost** [xjsender/HaoGist#1]
Thank you so much for working on this plugin. The Existing Gist plugin has been great, but with the lack of development, it seems to be a dead plugin.

I'm interested in a setting that like this:

``` json
{
    "auto_update_on_save": true
}
```

This was a feature that the other gist plugin used. Every time I opened a gist, made edits and hit save, it would upload the changes to the gist online.

Thanks once again for your work.

**Comment by xjsender** [comment]
@corndogcomputers , it's finished, I will release it at tonight, thanks for your suggestion.

**Comment by ghost** [comment]
:smile:

**Comment by xjsender** [comment]
Released
