### ISSUE TITLE
Option To Prevent Adding Gists Directory to Project?

### ISSUE THREAD

**Issue by dylan-k** [xjsender/HaoGist#2]
Great work on this package, by the way!

Is it possible to disable the feature that adds the Gists folder to the active project?

**Comment by xjsender** [comment]
@dylan-k , you don't want to see the workspace in the sidebar?

**Comment by xjsender** [comment]
@dylan-k , you answered a question in [this issue](https://github.com/condemil/Gist/issues/140) of `gist` plugin, did you check the issue owner?

**Comment by dylan-k** [comment]
ha ha. wow. that was you. That issue led me here.

but yes i opened this issue because it would be nice to have the option to disable the workspace in the sidebar. it closes all the folders I have open whenever I open a gist. that can slow somebody down if they're working on a big project.

**Comment by xjsender** [comment]
@dylan-k , it will be delivered tonight.
