### ISSUE TITLE
Does this work with a http_proxy?

### ISSUE THREAD

**Issue by SantoshSrinivas79** [xjsender/HaoGist#4]
Does this work with a http_proxy? I am getting a timeout error.

**Comment by xjsender** [comment]
@fountainhead , this plugin uses [requests](https://github.com/kennethreitz/requests) to perform http request, so you can get help on setting proxy by http://docs.python-requests.org/en/latest/user/advanced/#proxies

**Comment by xjsender** [comment]
@fountainhead , I don't have proxy environment, you need to try it by yourself, sorry.

**Comment by SantoshSrinivas79** [comment]
@xjsender thanks for your response. Can you please guide me where to set the configuration for `HaoGist`? I've never really used Python and hence wondering if you can help out.

The code from the `Gist` package which does this is below:

``` py
def api_request_native(url, data=None, token=None, https_proxy=None, method=None):
    request = urllib.Request(url)
    # print('API request url:', request.get_full_url())
    if method:
        request.get_method = lambda: method
    token = token if token != None else token_auth_string()
    request.add_header('Authorization', 'token ' + token)
    request.add_header('Accept', 'application/json')
    request.add_header('Content-Type', 'application/json')

    if data is not None:
        request.add_data(bytes(data.encode('utf8')))

    # print('API request data:', request.get_data())
    # print('API request header:', request.header_items())
    https_proxy = https_proxy if https_proxy != None else settings.get('https_proxy')
    if https_proxy:
        opener = urllib.build_opener(urllib.HTTPHandler(), urllib.HTTPSHandler(),
                                     urllib.ProxyHandler({'https': https_proxy}))

        urllib.install_opener(opener)

    try:
        with contextlib.closing(urllib.urlopen(request)) as response:
            if response.code == 204:  # No Content
                return None
            else:
                return json.loads(response.read().decode('utf8', 'ignore'))

    except urllib.HTTPError as err:
        with contextlib.closing(err):
            raise SimpleHTTPError(err.code, err.read())
```

**Comment by xjsender** [comment]
@fountainhead , just set environment variable for your operation system, you don't need to know anything about python.

**Comment by SantoshSrinivas79** [comment]
@xjsender 

Thank you. I don't want to do this through the environment variable so that other code I have does not break.

I got this working as follows.

``` py
import urllib.request as urllib

  proxyDict = {
              "http"  : "http://user:%23Cpassword%23C:server:port",
              "https" : "http://user:%23Cpassword%23C:server:port"
            }


self.res = requests.get(GIST_BASE_URL % "gists?per_page=1000", 
                headers=self.headers, proxies=proxyDict)
```

Is there a way I can add `proxies` globally so that every request call is not to be modified?

**Comment by xjsender** [comment]
I will release a new version to allow you to do it. thanks.

**Comment by xjsender** [comment]
@fountainhead , release v0.2.4 is available, I have added a new setting named `http_proxies` to perform request by proxies.
