### ISSUE TITLE
Unable to open gist

### ISSUE THREAD

**Issue by SantoshSrinivas79** [xjsender/HaoGist#5]
Hello,

I tried this package again. I am able to use it to list the available gists but once I try to open the file, I get the following error ... any ideas?

``` py
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'options'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'options'
```

**Comment by xjsender** [comment]
@fountainhead , how to replicate this issue? I just tried as your described but I can't get the same error with you.

Did you try to open a gist after restart sublime?

**Comment by SantoshSrinivas79** [comment]
@xjsender yes, I tried to restart but same error. I am on MacOSX with Sublime 3083.

``` py
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'options'
```

**Comment by xjsender** [comment]
@fountainhead , what's the HaoGist version?

**Comment by SantoshSrinivas79** [comment]
@xjsender I am using the latest version `0.2.5`.

The error image is below. Any idea how I can debug once I have extracted the package?

![hao-gist-error](https://cloud.githubusercontent.com/assets/1036163/9376543/202587d8-472c-11e5-8f44-95474d461619.gif)

**Comment by SantoshSrinivas79** [comment]
Works now. Not sure what the issue was

**Comment by Kristinita** [comment]
@SantoshSrinivas79 , is Sublime-GitHub problem, see [**#105**](https://github.com/bgreenlee/sublime-github/issues/105) issue.

Thanks.
